[vote]
start_vote='''
Закончился челлендж {theme}: {amount_photo} фоток ушло на голосование. 

Рассматриваем работы и голосуем вот тут: {link}
Голосовать можно за несколько фоток.

Победитель ачивку в клубе✖️, а фоточка отправится на обложку чата.

Итоги подведу {str_date}.

До окончания голосования предлагайте новые темы с тегом #тема

'''
will_you_post = '''
Начал голосование.
Если тебе не понравился текст — пришли свой, я выложу его.
Для того чтоб я запостил этот текст напиши <code>ОК</code>, любое другое сообщение от тебя я расценю как желаемый текст
-------

'''
no_vote_yet = "Эта голосовалка неактивна"
vote_started = "Голосовалка готова. Вот ссылка:"
no_username_bot = "Не получилось сгенерировать ссылку из-за отсутствия ника у бота"
wrong_link = "Неверная ссылка"
not_private_chat = "Голосовать можно только в приватном чате"
no_photos = "Фотографий с таким тегом нет"
unexpected_error = "Ошибка в cmd_start, голосовалка не сгенерировалась"
user_info = "Победитель: @{username}, {full_name}\nЛайков: {likes}"
err = "Не получилось поменять аватарку, разбирайтесь сами"

thanks_for_vote = "Голос принят. Спасибо, пирожочек!"
already_voted = "Ты уже проголосовал в этом челлендже"
greeting_message_vote = "Начинай голосовать! Можно за несколько фотографий."
no_winner = "Победителя нет. Ещё никто не проголосовал."
many_winners = "Победитель не один!"

[register_photo]
photo_registered = "Фотография принята"
photo_not_registered = "Ты уже прислал фотографию на этот челлендж. Если хочешь заменить на другую, напиши админу чатика."

[admin]
wrong_time = "Ошибка с указанием времени, отменяю создание челленджа"
you_are_not_admin = """Ты не админ.\n
             Чтобы стать админом в группе,
             добавь меня с правами админа в чат."""
choose_group = "Выбери чат"
choose_action = "Выбери действие"
are_you_sure_S = "Точно хочешь начать голосование?"
are_you_sure_F =  "Точно хочешь завершить голосование?"
vote_end = 'Голосование завершено. Результаты ниже.'
no_photos_at_end = "Ошибка. Нет фоток."
no_photos_at_start = "Нет фоток"

#maybe move to db
[contest]
create_greet_contest = '''
Пришли название для челленджа и срок в неделях (от 1 до 3).
<b>Примеры:</b>
1) #еда 1 неделя
2) #природа 2 недели
3) #вода 3 недели
Для отмены отправь слово <code>отмена</code>'''
start_contest='''
<b>Челлендж {num} —</b> {theme}

Свежие фото присылайте в чат с сегодня:
 - до вечера {week}, {date_str};
 - можно несколько, но на конкурс пойдёт первая;
 - фото должно быть сделано в промежутке с {date_now} по {date_str};
 - под фото для конкурса пишите тег {theme}

Тема трактуется свободно, но:
 - без животных,
 - без нюдсов,
 - без жестокости.

В конце пришлю форму для голосования. Победитель ачивку в клубе✖️, а фоточка отправится на обложку чата.

'''
cancel_contest = "Создание челленджа отменено"
will_you_post = '''
Тема для челленджа выбрана.
Если тебе не понравился текст — пришли свой, я выложу его.
Для того чтоб я запостил этот текст напиши <code>ОК</code>, любое другое сообщение от тебя я расценю как желаемый текст
-------

'''
err = "Произошла какая-то ошибка"

[add_admin]
create_greet_adm = "Перешли сюда сообщение от человека, которого ты хочешь сделать админом.\nУ него должен быть открыт профиль для пересылки.\n\nДля отмены отправь слово <code>отмена</code>"
add_adm = "Админ добавлен"
no_adm = "Админ не добавлен. Неверный юзернейм или закрытый профиль"
cancel_adm = "Добавление админа отменено"
err = "Произошла какая-то ошибка"


[del_admin]
delete_greet_adm = "Перешли сюда сообщение от админа, которого ты хочешь лишить администраторских прав.\nУ него должен быть открыт профиль для пересылки.\n\nДля отмены отправь слово <code>отмена</code>"
del_adm = "Админ удален."
no_adm = "Админ не удален. Неверный юзернейм или закрытый профиль"
cancel_adm = "Удаление админа отменено"
err = "Произошла какая-то ошибка"



[delete_photo]
create_greet_del = "Удалить фото можно одним из следующих способов:\n<b>1) </b>Перешли сюда сообщение от юзера, фото которого ты хочешь удалить.\n У него должен быть открыт профиль для пересылки.\n\n<b>2)</b> Пришли его юзернейм в формате @username\n\nДля отмены отправь слово <code>отмена</code>"
are_you_sure = "Подтверди удаление фотографии"
del_photo = "Фотография удалена"
no_user = "Юзер не найден, фотография не удалена"
cancel_del = "Удаление фотографии отменено"
no_understand = "Не понял ответ. Начни заново."
err = "Произошла какая-то ошибка"

##############################



